/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Colis;
import services.ColisService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mmajj
 */
public class ColisUI extends javax.swing.JInternalFrame {

    private ColisService fs ;
    private DefaultTableModel model =null;
    
    public ColisUI() {
        initComponents();
        fs = new ColisService();
        model = (DefaultTableModel) Coliis.getModel();
        loadColis();
    }
  private void loadColis() {
    model.setRowCount(0); // vider le tableau
    for (Colis c : fs.listeColis()) {
        model.addRow(new Object[]{
            c.getReference(),
            c.getPoids(),
            c.getVilleDestination()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        poitxt = new javax.swing.JTextField();
        viltxt = new javax.swing.JTextField();
        adtxt = new javax.swing.JButton();
        uptxt = new javax.swing.JButton();
        suptxt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Coliis = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 153));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des colis"));

        jLabel1.setText("Poids du Colis :");

        jLabel2.setText("Ville de destination :");

        adtxt.setBackground(new java.awt.Color(0, 255, 0));
        adtxt.setText("Ajouter");
        adtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adtxtActionPerformed(evt);
            }
        });

        uptxt.setBackground(new java.awt.Color(102, 102, 255));
        uptxt.setText("Modifier");
        uptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uptxtActionPerformed(evt);
            }
        });

        suptxt.setBackground(new java.awt.Color(255, 51, 51));
        suptxt.setText("Supprimer");
        suptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suptxtActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mmajj\\OneDrive\\Bureau\\Colis.png")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(adtxt)
                        .addGap(68, 68, 68)
                        .addComponent(uptxt)
                        .addGap(66, 66, 66)
                        .addComponent(suptxt)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(poitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adtxt)
                    .addComponent(uptxt)
                    .addComponent(suptxt))
                .addGap(70, 70, 70))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Les informations des colis"));

        Coliis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reference", "Poids", "Ville de Destination"
            }
        ));
        jScrollPane1.setViewportView(Coliis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adtxtActionPerformed
        // TODO double poids = Double.parseDouble(poitxt.getText());
    double poids = Double.parseDouble(poitxt.getText()); // lire le poids
    String ville = viltxt.getText();                     // lire la ville

    Colis c = new Colis(poids, ville);                  // créer le colis
    fs.ajouterColis(c);                                 // ajouter à la base

    loadColis();                                        // recharger le tableau
    JOptionPane.showMessageDialog(this, "Colis ajouté !");
    }//GEN-LAST:event_adtxtActionPerformed

    private void uptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptxtActionPerformed
        // TODO add your handling code here:
         int row = Coliis.getSelectedRow();
    if (row >= 0) {
        int reference = (int) model.getValueAt(row, 0);
        double poids = Double.parseDouble(poitxt.getText());
        String ville = viltxt.getText();

        Colis c = new Colis(reference, poids, ville);
        fs.modifierColis(c); // mettre à jour dans la base
        loadColis(); // recharger le tableau
        JOptionPane.showMessageDialog(this, "Colis modifié !");
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un colis !");
    }
    }//GEN-LAST:event_uptxtActionPerformed

    private void suptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suptxtActionPerformed
        // TODO add your handling code here:
        int row = Coliis.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un colis à supprimer !");
        return;
    }

    // Affiche un message Oui/Non
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Voulez-vous vraiment supprimer ce colis ?", 
        "Confirmation de suppression", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        int reference = (int) model.getValueAt(row, 0);
        fs.supprimerColis(reference);  // méthode à créer dans ColisService
        loadColis();                   // recharge le tableau
        JOptionPane.showMessageDialog(this, "Colis supprimé !");
    }
    }//GEN-LAST:event_suptxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Coliis;
    private javax.swing.JButton adtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField poitxt;
    private javax.swing.JButton suptxt;
    private javax.swing.JButton uptxt;
    private javax.swing.JTextField viltxt;
    // End of variables declaration//GEN-END:variables
}
