/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.SQLException;
import java.text.DateFormatSymbols;
import java.util.Locale;
import java.util.Map;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import services.LivraisonService;

/**
 *
 * @author mmajj
 */
public class grapheUI extends javax.swing.JInternalFrame {

    private final LivraisonService livraisonService;

    /**
     * Creates new form grapheUI
     */
    public grapheUI() throws SQLException {
        initComponents();

        livraisonService = new LivraisonService();
        afficherGraphiqueParMois();

    }

    private void afficherGraphiqueParMois() {

        Map<Integer, Integer> data = livraisonService.getLivraisonsParMois();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String[] mois = new DateFormatSymbols(Locale.FRENCH).getMonths();

        for (Map.Entry<Integer, Integer> e : data.entrySet()) {
            int index = e.getKey() - 1;
            if (index >= 0 && index < 12) {
                dataset.addValue(e.getValue(), "Livraisons", mois[index]);
            }
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Livraisons par Mois",
                "Mois",
                "Nombre",
                dataset
        );

        ChartPanel chartPanel = new ChartPanel(chart);

        // chartContainer = TON JPanel créé dans NetBeans Designer
        chartContaine.setLayout(new java.awt.BorderLayout());
        chartContaine.removeAll();
        chartContaine.add(chartPanel, java.awt.BorderLayout.CENTER);
        chartContaine.revalidate();
        chartContaine.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartContaine = new javax.swing.JPanel();

        chartContaine.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout chartContaineLayout = new javax.swing.GroupLayout(chartContaine);
        chartContaine.setLayout(chartContaineLayout);
        chartContaineLayout.setHorizontalGroup(
            chartContaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        chartContaineLayout.setVerticalGroup(
            chartContaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(chartContaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(chartContaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartContaine;
    // End of variables declaration//GEN-END:variables
}
