/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import dao.LivreurDao;
import entities.Livreur;
import java.sql.SQLException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import services.LivreurService;
/**
 *
 * @author mmajj
 */
public class LivreurUI extends javax.swing.JInternalFrame {
     private LivreurService lrs;
     

    /**
     * Creates new form LivreurUI
     */
    
    public LivreurUI() throws SQLException {
        initComponents();
      lrs = new LivreurService();
       loadLivreur();
       loadzonliv();
       loadvehicule();
       
       


        
    }
private void loadzonliv() {
        zoneliv.removeAllItems();
        zoneliv.addItem("Sud");
        zoneliv.addItem("Nord");
        zoneliv.addItem("Centre");
    }
private void loadvehicule() {
        vehiculeliv.removeAllItems();
        vehiculeliv.addItem("Moto");
        vehiculeliv.addItem("Camion");
        vehiculeliv.addItem("Vélo");
        vehiculeliv.addItem("Voiture");
    }
private void loadLivreur() {
        String[] columns = {"ID", "Nom", "Zone", "Véhicule"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        List<Livreur> liste = lrs.listeLivreurs();
        for (Livreur l : liste) {
            Object[] row = {l.getId(), l.getNom(), l.getZone(), l.getVehicule()};
            model.addRow(row);
        }
        tableliv.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameliv = new javax.swing.JTextField();
        zoneliv = new javax.swing.JComboBox();
        vehiculeliv = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addd = new javax.swing.JButton();
        modd = new javax.swing.JButton();
        suppp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableliv = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des livreurs"));

        jLabel1.setText("nom :");

        jLabel2.setText("zone :");

        jLabel3.setText("vehicule :");

        nameliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namelivActionPerformed(evt);
            }
        });

        zoneliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonelivActionPerformed(evt);
            }
        });

        vehiculeliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculelivActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mmajj\\OneDrive\\Bureau\\livreur.png")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(vehiculeliv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameliv)
                            .addComponent(zoneliv, 0, 238, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nameliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(zoneliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vehiculeliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        addd.setBackground(new java.awt.Color(0, 255, 0));
        addd.setText("ajouter");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });

        modd.setBackground(new java.awt.Color(102, 102, 255));
        modd.setText("modifier");
        modd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moddActionPerformed(evt);
            }
        });

        suppp.setBackground(new java.awt.Color(255, 51, 51));
        suppp.setText("supprimer");
        suppp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(suppp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(addd)
                .addGap(46, 46, 46)
                .addComponent(modd)
                .addGap(50, 50, 50)
                .addComponent(suppp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tableliv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id ", "nom", "zone", "vehicule"
            }
        ));
        jScrollPane1.setViewportView(tableliv);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namelivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namelivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namelivActionPerformed

    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed
        // TODO add your handling code here:
      
    String nom = nameliv.getText();
    String zone = (String) zoneliv.getSelectedItem();
    String vehicule = (String) vehiculeliv.getSelectedItem();

    if(nom.isEmpty() || zone == null || vehicule == null){
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
        return;
    }

    Livreur l = new Livreur(nom, zone, vehicule); 
    boolean ok = lrs.ajouterLivreur(l); 

    if(ok){
        JOptionPane.showMessageDialog(this, "Livreur ajouté avec succès !");
        loadLivreur();
        nameliv.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Échec de l'ajout !");
    }
        
    }//GEN-LAST:event_adddActionPerformed

    private void supppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supppActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableliv.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un livreur à supprimer !");
        return;
    }

    int id = (int) tableliv.getValueAt(selectedRow, 0);
    int confirm = JOptionPane.showConfirmDialog(this, "Supprimer ce livreur ?", "Confirmation", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        boolean ok = lrs.supprimerLivreur(id);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Livreur supprimé avec succès !");
            loadLivreur();
            nameliv.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Échec de la suppression !");
        }
    }
    }//GEN-LAST:event_supppActionPerformed

    private void moddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moddActionPerformed
        // TODO add your handling code here:
       int selectedRow = tableliv.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un livreur à modifier !");
        return;
    }

    int id = (int) tableliv.getValueAt(selectedRow, 0); 
    String nom = nameliv.getText();
    String zone = (String) zoneliv.getSelectedItem();
    String vehicule = (String) vehiculeliv.getSelectedItem();

    if(nom.isEmpty() || zone == null || vehicule == null){
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
        return;
    }

    Livreur l = new Livreur( nom, zone, vehicule); 
    boolean ok = lrs.modifierLivreur(l); 

    if (ok) {
        JOptionPane.showMessageDialog(this, "Livreur modifié avec succès !");
        loadLivreur();
        nameliv.setText("");
        zoneliv.setSelectedIndex(0);
        vehiculeliv.setSelectedIndex(0);
    } else {
        JOptionPane.showMessageDialog(this, "Échec de la modification !");
    }
    }//GEN-LAST:event_moddActionPerformed

    private void vehiculelivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculelivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiculelivActionPerformed

    private void zonelivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonelivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zonelivActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modd;
    private javax.swing.JTextField nameliv;
    private javax.swing.JButton suppp;
    private javax.swing.JTable tableliv;
    private javax.swing.JComboBox vehiculeliv;
    private javax.swing.JComboBox zoneliv;
    // End of variables declaration//GEN-END:variables

   
}
