/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mmajj
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ColisItem = new javax.swing.JMenuItem();
        LivreurItem = new javax.swing.JMenuItem();
        LivraisonItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        graphe = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        ColisItem.setMnemonic('o');
        ColisItem.setText("Colis");
        ColisItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColisItemActionPerformed(evt);
            }
        });
        fileMenu.add(ColisItem);

        LivreurItem.setMnemonic('s');
        LivreurItem.setText("Livreur");
        LivreurItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivreurItemActionPerformed(evt);
            }
        });
        fileMenu.add(LivreurItem);

        LivraisonItem.setMnemonic('a');
        LivraisonItem.setText("Livraison");
        LivraisonItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivraisonItemActionPerformed(evt);
            }
        });
        fileMenu.add(LivraisonItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        graphe.setMnemonic('h');
        graphe.setText("Graphe");

        jMenuItem2.setText("livraisons par mois");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        graphe.add(jMenuItem2);

        menuBar.add(graphe);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void ColisItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColisItemActionPerformed
        // TODO add your handling code here:
        ColisUI colisFrame = new ColisUI();
        desktopPane.add(colisFrame);
        colisFrame.setVisible(true);
    }//GEN-LAST:event_ColisItemActionPerformed

    private void LivreurItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivreurItemActionPerformed
        // TODO add your handling code here:
       try {
        LivreurUI livreurFrame = new LivreurUI();
        desktopPane.add(livreurFrame);
        livreurFrame.setVisible(true);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'ouverture de LivreurUI : " + e.getMessage());
    }
    }//GEN-LAST:event_LivreurItemActionPerformed

    private void LivraisonItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivraisonItemActionPerformed
        // TODO add your handling code here:
       try {
        LivraisonUI livraisonFrame = new LivraisonUI();
        desktopPane.add(livraisonFrame);
        livraisonFrame.setVisible(true);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'ouverture de LivraisonUI : " + e.getMessage());
    }
    }//GEN-LAST:event_LivraisonItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
        grapheUI frame = new grapheUI();
        desktopPane.add(frame);
        frame.setVisible(true);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'ouverture du graphe : " + e.getMessage());
    }


    }//GEN-LAST:event_jMenuItem2ActionPerformed
    private void grapheMenuMouseClicked(java.awt.event.MouseEvent evt) {
        // Créer une instance du graphe
      try {
        grapheUI graphFrame = new grapheUI();
        desktopPane.add(graphFrame);
        graphFrame.setVisible(true);
        graphFrame.setSelected(true);
    } catch (SQLException | java.beans.PropertyVetoException e) {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'ouverture du graphe : " + e.getMessage());
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    private void grapheMenuItemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        grapheUI graphFrame = new grapheUI();
        desktopPane.add(graphFrame);
        graphFrame.setVisible(true);
        try {
            graphFrame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ColisItem;
    private javax.swing.JMenuItem LivraisonItem;
    private javax.swing.JMenuItem LivreurItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu graphe;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
